services:
  - name: sistema-musical-emanuel
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    port: 3000
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - src/**
      ignoredPaths:
        - README.md